name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  build-noetic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-noetic-desktop-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: continuous_clustering
          target-ros1-distro: noetic
          vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/dependencies.repos"